version: '3.7'

services: 
    web:
        build:
            context: ../cfgis_api
            dockerfile: Dockerfile.prod
        command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
        volumes: 
            - ../cfgis_api/:/usr/src/app/
        expose: 
            - 8000
        env_file: 
            - ./.env.dev
        depends_on:
            - db
    db:
        image: postgres:12.0-alpine
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
        environment: 
            - POSTGRES_USER=hello_django
            - POSTGRES_PASSWORD=hello_django
            - POSTGRES_DB=hello_django_dev
    nginx:
        build: ./nginx
        ports: 
            - 1337:80
        depends_on: 
            - web            
volumes:
    postgres_data:                   