version: '3.7'

services: 
    web:
        build: ../cfgis_api
        command: python manage.py runserver 0.0.0.0:9800
        volumes: 
            - ../cfgis_api/:/usr/src/app/
        ports: 
            - 9800:9800
        env_file: 
            - ./.env.dev
        depends_on:
            - db
    db:
        image: postgres:12.0-alpine
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
        environment: 
            - POSTGRES_USER=hello_django
            - POSTGRES_PASSWORD=hello_django
            - POSTGRES_DB=hello_django_dev
volumes:
    postgres_data:                   